baseURL = 'https://vuczdy.netlify.app/'
languageCode = 'vi-vn'
title = 'vuczdy'

[menu]
  [[menu.main]]
  identifier = 'welcome'
  name = '/welcome'
  url = '/posts/welcome'
  [[menu.main]]
  identifier = 'about'
  name = '/about'
  url = '/about'

